### ISSUE TITLE
Improve test suite run time

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#141]
### Describe the Request

The test suite is getting a bit slow to run, and I think there are some easy wins to improve performance.

We'll first need to profile the tests and see which are taking the longest. I suspect a lot of time is spent in expensive fixtures (e.g., ones that launch an endpoint or signaling server in a separate process).

- We create a lot of one-time use signaling servers, endpoints, etc. as separate processes. The can be "session" scoped fixtures instead.
- Using "module/session" scoped fixtures could lead to some key clashes in stores so we should change any test case that uses a key to generate a unique key.
- This pattern (used a lot in `store_*_test.py`):
  ```python
  @pytest.mark.parametrize('store_fixture', FIXTURE_LIST)
  def test_xxx(store_fixture, request) -> None:
      store_config = request.getfixturevalue(store_fixture)
      store_config.type(store_config.name, **store_config.kwargs)
  ```
  could be changed to:
  ```python
  @pytest.fixture(params=FIXTURE_LIST)
  def store_impl(request) -> ...:
      store_config = request.getfixturevalue(request.param)
      store = store_config.type(store_config.name, **store_config.kwargs)
      yield store
      store.close()

  def test_xxx(store_impl) -> None: ...
  ```
  This should remove a lot of redundant code and sets us up for making the fixture have a larger scope by default.
  (Can also use `ids` param to make names of params more readable.)

### TODOs

- [x] Move all mocked classes to `testing/mocked`.
- [x] Remove `tmp_dir` fixture.
- [x] Make `endpoint` fixture session scoped.
- [x] Make signaling server fixture session scoped.
- [ ] Split signaling server fixture into an async and process version.
- [ ] Reuse endpoint server fixture in integration tests. We could have the main `endpoint` fixture spawn two? Also requires signaling server process fixture from before.
- [x] Handle uvloop better. Either enable or disable explicitly or use everywhere by default.
- [x] Change `Store` fixtures as noted above. Single `store_impl` fixture which itself is parametrized. Make session scoped.
- [x] Profile tests to see which remain as long and try to shorten where possible.

**Comment by gpauloski** [comment]
Adding more things to look for:
- handle uvloop better (some tests run code with the side effect of enabling uvloop)
  - just use uvloop for all tests?

**Comment by gpauloski** [comment]
Notes from before changes:

Tox Github Actions (including package installs):
- Py37: 54s
- Py38: 55s
- Py39: 53s
- Py310: 58s

Tox Personal desktop (just test run time):
- Py37: 12.12s
- Py38: 11.75s
- Py39: 12.80s
- Py310: 12.02s

**Comment by gpauloski** [comment]
I decided to skip splitting out the signaling server fixtures and changing the integration tests as they are less than 200ms each including setup/teardown.

After the changes running Tox on my personal desktop (just test run time):
- py37: 5.54s
- py38: 5.26s
- py39: 4.82s
- py310: 5.30s

That's 50-60% reduction in time!

The top tests are now:
```
0.33s setup    tests/integration/endpoints_test.py::test_endpoint_transfer
0.28s setup    tests/integration/endpoints_test.py::test_endpoint_proxy_transfer
0.25s setup    tests/integration/endpoints_test.py::test_proxy_detects_endpoint
0.23s call     tests/store/endpoint_test.py::test_chunked_requests
0.21s call     tests/integration/endpoints_test.py::test_proxy_detects_endpoint
0.15s call     tests/p2p/connection_test.py::test_p2p_connection
0.13s call     tests/endpoint/serve_test.py::test_chunked_data
0.13s call     tests/integration/endpoints_test.py::test_endpoint_transfer
0.12s call     tests/p2p/client_test.py::test_connect_exceptions
0.11s call     tests/p2p/manager_test.py::test_p2p_messaging
0.11s call     tests/p2p/manager_test.py::test_p2p_connection
0.11s call     tests/endpoint/endpoint_peering_test.py::test_set
0.11s call     tests/p2p/connection_test.py::test_p2p_connection_multichannel
0.11s call     tests/store/dim/ucx_test.py::test_ucx_store
0.10s call     tests/integration/endpoints_test.py::test_endpoint_proxy_transfer
0.10s call     tests/p2p/manager_test.py::test_p2p_connection_error_from_server
0.10s setup    tests/store/endpoint_test.py::test_no_endpoints_match
```
