### ISSUE TITLE
Favor composition over inheritance in `Store`

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#192]
# Motivation

Currently, we favor inheritance over composition (a classic Python code smell).
```python
T = TypeVar('T')
FactoryType = Callable[[], T]
KeyT = TypeVar('KeyT', bound=NamedTuple)

class Factory(Generic[T]): ...

class Proxy(Generic[T]):
    def __init__(self, factory: FactoryType[T]) -> None: ...

class StoreFactory(Factory[T], Generic[KeyT, T]): ...

class Store(Generic[KeyT], metaclass=ABCMeta): ...

class StoreImplKey(NamedTuple): ...

class StoreImpl(Store[StoreImplKey]): ...
```
The result of this structure is a lot of annoying coupling between `Store` and the implementations.

For example, consider the `MultiStore` in #126 ([implementation](https://github.com/proxystore/proxystore/blob/d71bafe18e2685c9c854b7b554a741d1da783a92/proxystore/store/multi.py#L142)) where every single method of `Store` needed to be overridden, or the `GlobusStore` which has to reimplement a number of `Store` methods because of the way composing a `GlobusStoreKey` works with getting Globus Transfer task IDs.

We also end up with a confusing hierarchy of generic types that leads to confusion when writing code that one would thing mypy should just accept.
```python
stores = {LocalStore(): Policy()}
MultiStore('multi', stores=stores)
# mypy error: Argument "stores" to "MultiStore" has incompatible type "Dict[LocalStore, Policy]"; expected "Union[Mapping[str, Policy], Mapping[Store[Any], Policy], Sequence[_StorePolicyArgs]]"
```

I also face issues with the fact that NamedTuples are not a real types
```
Argument 1 to "exists" of "LocalStore" has incompatible type "NamedTuple"; expected "LocalStoreKey"
```
when type hints are more narrow than `Store[Any]`.

# Proposal

Separate the `Store` from implementation by factoring out implementations into `Connector`s.
A `Connector` is an interface to byte-level object storage and no more (i.e., no serialization, caching, proxies to worry about).
The `Store`, now a concrete type, is initialized with a `Connector` and adds all the ProxyStore "magic" on top (serialization, caching, stats, proxies, etc.).

## `Connector`

```python
@runtime_checkable
class Connector(Protocol[KeyT]):
    def close(self) -> None: ...
    def config(self) -> dict[str, Any]: ...
    def from_config(self, config: dict[str, Any]) -> None: ...
    def evict(self, key: KeyT) -> None: ...
    def exists(self, key: KeyT) -> bool: ...
    def get(self, key: KeyT) -> bytes: ...
    def get_batch(self, Sequence[KeyT]) -> list[bytes]: ...
    def put(self, obj: bytes) -> KeyT: ...
    def put_batch(self, objs: Sequence[bytes]) -> list[KeyT]: ...
```

`Connector` implementations can provide context manager functionality for convenience, though it is not a required part of the protocol as the `Store` will not use it.

## `Store`

```python
class StoreFactory(Generic[KeyT]):
    def __init__(self, key: KeyT, store_config: StoreConfig[KeyT], *, deserializer: DeserializerT, evict: bool = False) -> None: ...
    # Rest of interface is same with addition of __call__ so StoreFactory does
    # not inherit from proxystore.factory.Factory

class Store(Generic[KeyT]):
    def __init__(self, connector: Connector[KeyT], serializer: SerializerT | None, deserializer: DeserializerT | None, cache_size: int = 16, stats: bool = False) -> None: ...
    @classmethod
    def from_config(cls, config: StoreConfig[KeyT]) -> Store[KeyT]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, ...) -> None: ...
    def __repr__(self) -> str: ...
    def close(self) -> None: ...
    def config(self) -> StoreConfig[KeyT]: ...
    def evict(self, key: KeyT) -> None: ...
    def exists(self, key: KeyT) -> bool: ...
    def get(self, key: KeyT, *, deserializer: DeserializerT, default: Any = None) -> Any: ...
    def is_cached(self, key: KeyT) -> bool: ...
    def proxy(self, obj: T, *, serializer: SerializerT, deserializer: DeserializerT) -> Proxy[T]: ...
    def proxy_batch(self, objs: Sequence[T], *, serializer: SerializerT, deserializer: DeserializerT, evict: bool = False) -> list[Proxy[T]]: ...
    def proxy_from_key(self, key: KeyT, *, deserializer: DeserializerT, evict: bool = False) -> Proxy[Any]: ...
    def locked_proxy(self, obj: T, *, serializer: SerializerT, deserializer: DeserializerT, evict: bool = False) -> ProxyLocker[T]: ...
    def set(self, obj: bytes, *, serializer: SerializerT) -> KeyT: ...
    def set_batch(self, objs: Sequence[bytes]) -> tuple[KeyT]: ...
    def stats(self, key_or_proxy: KeyT | Proxy[Any]) -> dict[str, TimeStats]: ...

class StoreConfig(TypedDict, Generic[KeyT]):
    name: str
    connector_type: type[Connector[KeyT]]
    connector_config: dict[str, Any]
    serializer: SerializerT | None
    deserializer: DeserializerT | None
    cache_size: int
    stats: bool
```

The `Store` methods can also take variable `**kwargs` to pass along to the `Connector` if the `Connector` has extra options.

### Benefits

- No inheritance or abstract base classes.
  - No subtypes overriding parent types (yay Liskov substitution principle!)
  - E.g., GlobusStore no longer has to override `set` and the proxy methods.
- `Store` interface stays the same (for the most part).
  - `set_bytes`, `get_bytes`, `create_key` are removed but these were never really intended to be a part of the public API.
  - Instead of having different `Store` subtypes, we have one `Store` thats generic w.r.t. the key: `Store[KeyT]`
  - Most annotations were `Store[Any]` rather than a specific implementation so compatibility should be strong.
- Implementing new `Connector`s is easier and can be tested independently.
  - E.g., a third-party package could provide a connector and not need to mess with any ProxyStore stuff.
  - `DIMStore`s could be a third-party package of `Connector`s instead. Would also solve our headaches with integration tests for those codes.
- `MultiStore` becomes `MultiConnector` and is wayyyyy less code.
  ```python
  class MultiConnector:
      def __init__(self, connectors: dict[Connector, Policy]) -> None: ...
  ```
  - Would require having `Store` methods takes `**kwargs` and pass them onto the `Connector` methods.

- Minor:
  - Addressing #5 and #124 should be easier.
  - #4 can be closed as key generation is unique to `Connector`.
  - #148, #151, #159, and #166 can potential move to their own repo where it's easier to test and integrate on them.

#### Breaking Changes

This is a breaking change because `Store` intialization is different (but usage is the same!).
Before:
```python
store = RedisStore('my-store', host=host, port=port, cache_size=16, stats=True)
```
After:
```python
store = Store('my-store', RedisConnector(host, port), cache_size=16, stats=True)
```

We can maintain backwards compatibility wrappers for one full minor release cycle with deprecation warnings.
```python
# proxystore/connectors/redis.py

class RedisKey(NamedTuple):
    key: str

class RedisConnector:
    def __init__(self, host: str, port: int) -> None: ...
```
```python
# proxystore/store/redis.py

class RedisStore(Store[RedisKey]):
    def __init__(self, name: str, *, host: str, port: int, **kwargs) -> None: ...
        warnings.warn(DeprecationWarning, ...)
        connector = RedisConnector(host, port)
        super().__init__(name, connector, **kwargs)
```

#### `NamedTuple` for Keys

This does not address the annoyances with `NamedTuple` types when you have `store: Store[RedisKey]` and you try to pass a tuple as the key. I'm not 100% sure what to do about this. It's nice to have keys as tuples because they are widely compatible and the `NamedTuple` aspect gives nice named attribute access and typing.

At the very least, this proposal should make it easier to change en-masse the types of `KeyT` if needed.

#### Dev hours

This would require a fair amount of code changes. See the roadmap below.

## Roadmap

- [x] Create `Connector` protocol. (easy)
- [x] Refactor `Store` to be a concrete type with a `connector` parameter. (easy)
- [x] Move the old `Store` implementations to `Connector`s. (easy---just ripping out extra stuff)
- [x] Add backwards compatible `Store` wrappers with deprecation warnings. (easy)
- [x] Update `StoreFactory` to use `Store` "configs" (in place of old `store_type`/`store_kwargs`). (easy)
- [x] Update test suite to test `Connector` and `Store` separately. (hard)
- [x] Add back `dim` stores removed for speeding up development.
- [x] Add low level tracking on connector operations.
- [x] Make `Factory` a protocol.
- [x] Update docs with new usage. (easy)
- [x] Update examples.

### Final breaking changes

- `MultiConnector` raises `RuntimeError` instead of `ValueError` if no policy is found.
- Stats dicts will no longer have `set_bytes`/`get_bytes` (or size info)
- Key types changed from `XStoreKey` to `XKey`
- Many utils changed from `proxystore/store` to `proxystore/connectors`.
- `MultiStore` arguments changed.
- `DIMStore` shims not added back.
