### ISSUE TITLE
Support blocking/future-like semantics on Proxies

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#303]
### Describe the Request

It would be useful to support the use case where we want to create a proxy to an object which will exist in the future. In essence, to create a proxy with future-like semantics where the producer creates the "future-proxy" and at some later time can set the result of the "future-proxy." A consumer which resolves the "future-proxy" will block until the result has been set.

The primary caveat to this is that some `Connector` implementations need the object prior to generating a key for it. As far as I know, this may only apply to the `GlobusConnector` which needs to include the Globus transfer ID in the object's key.

**Comment by gpauloski** [comment]
## Proposal
Here's my proposal for a basic implementation.

The `Store` is extended with a `future()` method which returns an instance of `ProxyFuture`.
```python
class Store(Generic[ConnectorT]):
    def future(
        *,
        evict: bool = False,
        serializer: SerializerT | None = None,
        deserializer: DeserializerT | None = None,
        **kwargs: Any,
    ) -> ProxyFuture[T]:
        ...
```

The `ProxyFuture` implements a [`concurrent.futures.Future`](https://github.com/python/cpython/blob/7cce26bcd99d444878c211767794b72bc791ff97/Lib/concurrent/futures/_base.py#L325)-like interface with one additional method `proxy()`.
```python
class ProxyFuture:
    def set_result(obj: T) -> None: ...
    def set_exception(exp: Exception) -> None: ...
    def result() -> T: ...
    ...  # Rest of concurrent.futures.Future interface

    def proxy() -> Proxy[T]:
        # Creates Proxy using PollingStoreFactory
        ...
```

Because a `Proxy` initialized with a `StoreFactory` instance will immediately error if the resolve fails, we'll need to create a new factory type which implements a blocking resolve. Because the `Connector` types have no support for blocking gets at the moment, we'll take the simpler approach of implementing a `PollingStoreFactory`. This can be a simple extension of `StoreFactory` that modifies the `resolve()` method to poll. Both the `ProxyFuture` and `PollingStoreFactory` will need to have initialization parameters for the polling (e.g., polling interval and timeout).

This proposal will require two changes to the `Connector` protocol:
- Add `new_key(obj: bytes | None = None)` so that the `ProxyFuture` can be initialized with a key before the object exists. Note that some `Connector` implementations may not be able to implement this and will raise `NotImplementedError`s.
- Add `set(key: KeyT, obj: bytes)` in order to implement `ProxyFuture.set_result()`.

Additional Requirements:
- `ProxyFuture` is serializable
- Add a guide for working with proxies.

## Example
Here we invoke two remote functions at the same time that have a data dependency with each other. The *producer* function gets the `ProxyFuture` instance which it can use to set the result, and the *consumer* function get the `Proxy` which will block once the data is needed.
```python
def remote_foo(future: ProxyFuture) -> ...:
    # Compute
    future.set_result(...)

def remote_bar(proxy: Proxy[...]) -> ...:
    # Uses proxy normally, blocking during resolve

with Store(...) as store:
    future = store.future()

    # Parsl or Globus Compute-like invocation of function
    foo_result_future = invoke_remote(remote_foo, future)
    bar_result_future = invoke_remote(remote_bar, future.proxy())

    foo_result_future.result()
    bar_result_future.result()
```

## Roadmap
- [ ] Move `StoreFactory` to its own module in anticipation of supporting more factory types.
- [ ] Add `new_key()` and `set()` to `Connector`.
- [ ] Add `ProxyFuture` and `Store.future()`.
- [ ] Add guide/tutorial.

The first two will be handled in separate issues/PRs. The last two will be handled in the PR which addresses this issue.
